### ISSUE TITLE
Tracker: TightCoder

### ISSUE THREAD

**Issue by dk1a** [latticexyz/mud#1132]
- [x] Revisit `TightCoder` naming - decided to keep it
- [x] ~consider moving it to a separate package (TightCoder doesn't really depend on `store`, except `Slice.sol` which is complicated)~ not worth it - it's useless outside of `store`, and separating it would be complicated (requires Slice and Memory as yet another package)
- [x] ~add a typescript rendering utility in addition to pre-rendered solidity stuff~ making a generalized tight encoder is needlessly complicated; codegen was refactored to use typescript though
- [x] ~(using the utility) try preallocate for all, encodePacked statics, and direct encode dynamics in 
 `store/ts/codegen/record.ts` (see https://github.com/latticexyz/mud/pull/422#discussion_r1119458406)~ making a generalized tight encoder is needlessly complicated; gas implications likely not significant; may be worth exploring again in the future
- [x] Revisit `_encodeToLocation` in `TightCoder` (see https://github.com/latticexyz/mud/pull/422#discussion_r1119465262) https://github.com/latticexyz/mud/pull/1210
- [x] Remove sanity checks in `TightCoder` (see https://github.com/latticexyz/mud/pull/422#discussion_r1119465344)
- [x] ~consider removing solidity stuff, keeping only the js utility (not sure, seems bad)~ making a generalized tight encoder is needlessly complicated

**Comment by dk1a** [comment]
> Revisit TightCoder naming

some proposed alternatives from https://github.com/latticexyz/mud/pull/387:
DataPack, DataPacker, BytePacker, BytesPacker, DataCoder, ByteCoder, Serializer

**Comment by alvrs** [comment]
closing this as since all todos are done
