### ISSUE TITLE
Tracker: v2 config

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#2435]
### Things left to do

- [ ] split out shorthand config from main config resolution flow and turn them into a "plugin"
- [ ] don't default tableId to `0x` but instead throw if no `tableId` is provided
- [ ] transformer from v2 config output to v1 config output to be consumed by existing tooling

**Comment by yonadaaa** [comment]
Static arrays cause a type error 
<img width="770" alt="image" src="https://github.com/latticexyz/mud/assets/29184158/654d25e2-c444-42ff-9f98-7a160c3714ea">

**Comment by yonadaaa** [comment]
No type error if `schema` is a string 
<img width="333" alt="image" src="https://github.com/latticexyz/mud/assets/29184158/e77a4972-6f39-4db7-a6ed-eb6242592823">
