### ISSUE TITLE
v2 tablegen

### ISSUE THREAD

**Issue by dk1a** [latticexyz/mud#438]
Tablegen is growing big enough that I need a tracker to remember what to do

#### PRs:
- #402
- #437
- (store, indirectly related) #434

### General

- [x] StoreConfig
- [x] Basic generator
- [ ] Schema and Table generator (#437)
- [ ] Singleton Schema/Table (#437)
- [ ] Client definitions
- [ ] Enum wrapper
- [ ] Static array wrapper
- [ ] Omniimport (?)
- [ ] Foreign keys (?)
- [ ] Prototypes (?)
- [ ] Schema-from-RPC mode

### World

Much of world stuff is not very tablegen-related right now, and @alvrs is working on deploy

- [ ] Register route/table
- [ ] Metadata
- [ ] ... more?

### Arrays
Depends on StoreCore

- [ ] Push (started with StoreCore in #434)
- [ ] Pop
- [ ] SetItem
- [ ] Set (the data structure) (is this even related to tablegen?)

### Misc
- [ ] Better errors (subclasses instead of a list)
- [ ] Better config validation (zod?)
- [ ] Autoprettier
- [ ] `.ts` `.cts` extensions support (?)

**Comment by alvrs** [comment]
Can you elaborate a bit on these points:
- User-defined type wrapper
- Types reuse

**Comment by dk1a** [comment]
> User-defined type wrapper

(currently we have abi types and enums)
Allow [solidity's user-defined value types](https://docs.soliditylang.org/en/latest/types.html#user-defined-value-types), which are abi types but named differently, implementation would be very similar to enums. Then they can be reused across tables (you could have `type Entity is bytes32` for ECS for example)

> Types reuse

(currently we generate `Types.sol` with enums)
- Allow generating 1 struct for several tables with identical data, so the data can be seamlessly passed between tables
- Allow types to be imported from a user-defined (not autogenerated) file
- Allow structs to be imported from a manual user file

**Comment by alvrs** [comment]
Seems like `Allow types+structs to be imported from a user-defined (not autogenerated) file` would solve both user-defined type wrappers and the two latter points of types reuse. Moved this to its own issue: #1139
