### ISSUE TITLE
mud v2 QA checklist

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#694]
- [ ] build/deploy on windows
- [ ] build/deploy on linux
- [ ] build/deploy app with next.js (i.e. webpack instead of vite)
- [ ] deploy to various testnets
  - [ ] eth goerli/sepolia (non-rollup)
  - [ ] op testnet and/or base testnet (eip-1559)

**Comment by holic** [comment]
from [discord](https://discord.com/channels/865335009915961364/1029021674605129728/1101951715508486275):
> We have been trying to test MUD (v1 and v2) on substrate based EVMs (https://github.com/paritytech/frontier) such as Moonbeam. Contracts deploy fine, but when we call functions on the contracts (executeTyped on IncrementSystem for v1, installRootModule on World for v2) we get exceeds block gas limit. This happens with frontier template nodes, moonbeam nodes and on moonbase alpha testnet (https://moonbase.moonscan.io/tx/0xd0d23e1712c0ee9d64589fa4586d74f6da6a48014ccf013446b3b2c0794ea2e4). Any ideas? Has anyone else attempted to use MUD on a Substrate EVM chain? Thanks!

**Comment by jfrank-summit** [comment]
I did a bit more testing yesterday, and I did get `installRootModule` to work on moonbase alpha testnet. Also, digging into a Moonbeam dev node, it wasn't an exceeds block gas limit error, but  something else happening that shows a similar error during the deploy-v2 call but if I make the same call via remix it works 🤷 

I was still getting "exceeds block gas limit" when running against a frontier template node, but we will dig deeper into this on the frontier side this week. If I find anything useful I will update you. Thanks!
