### ISSUE TITLE
dev tools checklist

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#777]
In an effort to land https://github.com/latticexyz/mud/pull/689 without the PR dragging on forever, I left a lot of TODOs on the table that I'd like to come back to over time:

- [ ] add readme/docs
- [ ] fix tab index when ui is hidden
- [ ] see if react-table can help with table rendering (esp for large event logs)
- [x] expose unmount function
- [ ] make sure we clean up global listeners (mostly in useStore)
- [x] turn table fields into columns (instead of a single value column with json blob)
- [ ] move selected table into app state so we can remember it between navigation
- [ ] populate recent txs on load
- [ ] cache tx receipts in IndexedDB?
- [ ] figure out what to do with tx replacements (gas, nonce, etc)
- [x] emit tx failures during gas estimation
- [x] export viem chain object for lattice testnet from somewhere
- [ ] figure out hot reloading (any change causes the whole dev UI to refresh/lose state)
  - I think this might be because locally we use the build files from packages rather than source files, so the example project vite pipeline can't know which files to hot swap - it only has one large bundle
- [x] figure out why sometimes refresh with `cache=false` doesn't load in all historical events, only recent ones
- [ ] why are some tables missing metadata (`mudstore:schema` in particular) at the time of the store event?
- [x] is there a quick/hacky way to expose failed tx estimates?
- [x] move `TableId` to common package
- [ ] viem's decoding can throw if the ABI is missing data, need to handle that so the app doesn't explode
  - [ ] `decodeFunctionData`
  - [x] `decodeEventLog` 
- [ ] add more error boundaries throughout
- [x] should start collapsed
- [x] should remember collapsed state + page between browser reloads
- [x] button/hint isn't visible on dark backgrounds (see emojimon)
- [x] fix z-index (see emojimon encounters)
- [ ] some way to resize? pop out?
- [x] show world address
- [ ] CSS still leaks (mostly from body, see phaser example), try shadow dom?
- [x] show mud version in use?
- [x] fix balance (showing as wei rather than eth)
- [x] add full tx hash to truncated tx `title`
- [x] make tx hash clickable to chain's block explorer (if available)
- [ ] show sync state (incl. block number)
- [ ] react linter for effect deps

**Comment by holic** [comment]
closing as dev tools is deprecated in favor of explorer
